### ISSUE TITLE
Enforce buffer size to be an odd number

### ISSUE THREAD

**Issue by VMois** [VMois/remedian-js#1]
If the buffer size is an odd number it simplifies the median calculation. Odd numbers are suggested for the Remedian algorithm. We should only allow users to put odd numbers.

https://github.com/VMois/remedian-js/blob/040544daf3877d0a3d7ed74b4d77c92649743c70/index.js#L15

**Comment by chadvidovcich** [comment]
Hey @VMois ! I'd like to take a look at this issue. 

Would you like the process to **quit** if an even number is used? Or would you like it to print an error and **continue with the default** size of 3?

**Comment by VMois** [comment]
Hey @chadvidovcich. Thank you for helping.

Let's throw an error. We have two scenarios you will need to account for:

1. `bufferSize` is less or equal to 1, [throw an error](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/throw) and notify users that the allowed bufferSize value must be an odd number greater or equal to 3.

2. In case, the number is above 1 and is even, throw an error that notifies the user that the desired bufferSize is an odd number greater or equal to 3.

Please, add two test cases to test the above scenarios.

Also, in your commit message, please, use `closes #1` and put it in a new line. Thank you!

**Comment by chadvidovcich** [comment]
@VMois , Glad to be able to help!

I'll get started on the changes and submit a new PR when ready. Thanks for the clear direction.

**Comment by chadvidovcich** [comment]
@VMois I have submitted PR #11 for this issue. 👍🏼
